# GitHub Pages配置
title: "第二章数据可视化平台"
description: "基于第二章知识的数据可视化Web平台"
baseurl: ""
url: "https://fangxinyi123.github.io/dierzhang2"
theme: jekyll-theme-minimal

# 排除文件
exclude:
  - .gitignore
  - README.md
  - _config.yml

# 插件
plugins:
  - jekyll-sitemap